#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export FZF_DEFAULT_COMMAND='fd --type f'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

DEBEMAIL="randomizedthinking@gmail.com"
DEBFULLNAME="Gang Liang"
export DEBEMAIL
export DEBFULLNAME

source ~/02-computing/shell/zsh-config/X.zsh
source ~/02-computing/shell/zsh-config/basic.zsh
source ~/02-computing/shell/zsh-config/alias.zsh
source ~/02-computing/shell/zsh-config/fzf.zsh
source ~/02-computing/shell/zsh-config/music.zsh
source ~/02-computing/shell/zsh-config/tmux.zsh
source ~/02-computing/shell/zsh-config/sagemaker.zsh
source ~/02-computing/shell/zsh-config/snowflake.zsh
source ~/02-computing/shell/zsh-config/functions.zsh
source ~/02-computing/shell/zsh-config/key-bindings.zsh
source ~/02-computing/shell/zsh-config/python.zsh
source ~/02-computing/shell/zsh-config/api-keys.zsh
source ~/02-computing/shell/zsh-config/pnpm.zsh
